### ISSUE TITLE
Coq: exited abnormally with code 141

### ISSUE THREAD

**Issue by jonleivent** [psteckler/ProofGeneral#22] opened 2016-09-17 02:11 UTC
While working with script wavl-noauto.v from [https://github.com/jonleivent/mindless-coding-phase2](url), using PG version 284b242, Emacs 24.4.1, Coq 8.6 (3e794be), got a pop-up window with title "Information" and text "Coq: exited abnormally with code 141" to appear.

The approximate way to replicate this:
Open file wavl-noauto.v.  Scroll down to the Fixpoint Insert function Section Insert.  Just prior to the function's first line, issue toolbar GoTo.  What for locked region to blue.  Move cursor about half-way down this function, and issue GoTo.  Wait until processing starts, plus a little more, then ^C^C.  The final tactic step that was processed gets turned pink.  Move the cursor past this function's Qed, and do GoTo.  Sometimes, the error pops up, other times not.  However, that pinked tactic remains pink.

**Comment by psteckler** [comment] 2016-09-19 18:40
I was able to reproduce the abnormal exit once, and the remains-pink error several times.

I'm not sure why coqtop is crashing, the XML traffic looks OK to me. I see a message indicating that `insert' has been defined, which contains the state id corresponding to the submission of the Qed. 

I could not get CoqIDE to crash coqtop in the same way.

**Comment by psteckler** [comment] 2016-09-26 15:55
The exit with code 141 bit appears to be a Coq-side issue. It happens sometimes when PG sends a SIGINT. Since we've lost all state in that case, we can't get back to the point of the interrupt. I think PG should retract the buffer in this case.

**Comment by psteckler** [comment] 2016-09-26 22:26
I think I've fixed the remains-pink issue. Pink indicates the "queued" region. When an interrupt occurs, now PG flushes the queue, and sets the end of the queued region to the last span that was submitted with a good response.

If Coq crashes, there's not much PG can do except restart Coq.

**Comment by jonleivent** [comment] 2016-09-28 18:14
I git this error code 141 a lot now on ^C^C, and PGxml does restart after it.  If this is the best one can do, then I suggest having a "synchronous" mode that works without any asynchrony (unless lazy behaves that way) - on other words, like normal PG, so that users that need to debug long-running tactics, and hence do ^C^C a lot, don't keep having to restart coqtop.

**Comment by psteckler** [comment] 2016-10-03 15:17
If `coq-allow-async-proofs` in coq/coq-system.el is nil, you should get synchronous behavior, a la vanilla PG. 

If you do get an exit-141, can you send me the \*coq-log\*. The log is no longer flushed between restarts, so maybe there's some clue there why Coq crashes.

**Comment by jonleivent** [comment] 2016-10-05 17:12
I just tried setting `coq-allow-async-proofs` to nil.  It does yield synchronous behavior, but the pale blue/pink script highlighting isn't as with vanilla PG.  Not a big deal, unless it is showing that there is still some asynchronous behavior going on that ^C^C could trash...

**Comment by psteckler** [comment] 2016-10-05 17:34
I think that's because PG-XML turns items blue as soon as they're queued to send to Coq, where vanilla PG likely waits until they're sent to Coq.

**Comment by psteckler** [comment] 2016-10-06 20:05
I just noticed an exit-141 crash after doing a C-c C-c, which working on issue #45.

I think this is a Coq bug, somehow an interrupt puts it in a bad state. The crash seems to happen in a delayed way, where it can process some script after the interrupt resets to a valid state, and some lines later, it dies.

**Comment by psteckler** [comment] 2016-10-19 15:47
I think exit-141 bug is fixed now. PG was sending an interrupt to the shell containing Coq, not to Coq itself.

**Comment by psteckler** [comment] 2016-10-19 18:53
Still get the error sometimes.

**Comment by ejgallego** [comment] 2016-10-19 19:58
This usually means coq died with a `SIGPIPE`, ummm... Can you reproduce this with no workers at all?

**Comment by psteckler** [comment] 2016-11-10 16:12
If I disable async processing, I'm unable to trigger an exit-141.

**Comment by ejgallego** [comment] 2016-11-10 16:52
Yeah so it looks like a worker pipe broke... did you already submit a bugzilla report ? IMHO this looks like a 100% Coq bug.

**Comment by psteckler** [comment] 2016-11-10 18:27
Yes, I believe it's because a worker pipe broke, but I think it's not a Coq bug.

I'm invoking Coq using an Elisp function that starts a shell, so I can do redirection.

The Elisp function interrupt-process gives you two choices: either send a SIGINT to the immediate process, in this case a shell, or to the process group associated with the process' pty, which in this case I believe includes the workers. 

I don't see the behavior if I send a SIGINT via the command line. I'll see if I can target the SIGINT more narrowly.

**Comment by psteckler** [comment] 2016-11-10 18:59
I don't see a way a way to target signals more narrowly from Elisp. The code that controls how interrupts are targeted is some C in the Emacs sources.

PG could call `ps` and `kill` on Linux, but that's not portable and I don't think there's a guarantee that these are installed.

On Emacs 25, we could install a plugin that does the magic via C code, but most users are likely on Emacs 23 or 24.

One solution would be to immunize the Coq workers from SIGINT with a no-op handler. Is that possible?

**Comment by psteckler** [comment] 2016-11-10 21:37
I tried installing a do-nothing signal handler in the proof worker code. I confirmed that it gets called when PG sends a SIGINT by having it write something to a file.

With a do-nothing handler installed, I still get an exit-141, but it seems to happen much later now, after many steps in Coq.

I also tried having the proof worker signal handler raise Sys.Break, and the exit-141 happens immediately. 

That suggests that the exit-141's I was seeing originally come from the workers getting killed directly by the SIGINT. The delayed exit-141's are happening, I think, by the parent coqtop somehow killing the workers at a later point. If so, that's a Coq bug.

**Comment by ejgallego** [comment] 2016-11-11 15:53
I am not sure that installing a signal handler in the workers is the right solution. I also find strange that emacs has to start the coq slave through a shell, I tried to have a look to the sources but I couldn't find the exact magic, what kind of redirection is needed?

**Comment by psteckler** [comment] 2016-11-11 16:39
The shell is used to redirect stderr, otherwise error messages get mingled with XML, if you recall.

I was looking at the Elisp manual, and there may be another way to invoke Coq that keeps stderr separate, without a shell. That would allow sending a SIGINT only to the parent Coq process.

**Comment by ejgallego** [comment] 2016-11-12 13:29
IMO any error message printed in the stderr is a Coq bug. All printing should go throu the proper channels.

**Comment by psteckler** [comment] 2016-11-12 15:57
As I recall, the output on stderr comes from camlp4. It can also happen with the -debug flag, see #2 .

**Comment by ejgallego** [comment] 2016-11-13 14:34
I see. IMO both are bugs in Coq that can be fixed.

**Comment by psteckler** [comment] 2016-11-14 17:36
The other method to invoke processes that allows capturing stderr separately is `make-process`, and it's Emacs 25, alas. Even my recently-updated Linux Mint 18 provides Emacs 24.5.

Elisp does have a way to list processes and send signals, let me see if I can make that work.

**Comment by psteckler** [comment] 2016-11-14 18:28
I've committed a change where Emacs sends the SIGINT just to the shell's child (namely Coq), using some Elisp primitives for processes and signals.

I did get an exit-141 error once in about 10 tries; it seems a more robust mechanism than before.

**Comment by psteckler** [comment] 2016-11-17 21:11
I'm closing this one, because PG was formerly sending a SIGINT to workers which resulted in an exit-141. That was the essential bug. Currently, PG sends the SIGINT to the parent Coq process, and I've only gotten an exit-141 once out of many tries -- that one is likely a Coq bug.

**Closed by psteckler** 2016-11-17 21:11 UTC
