### ISSUE TITLE
Wrong state id for Add

### ISSUE THREAD

**Issue by maximedenes** [psteckler/ProofGeneral#3] opened 2016-08-19 14:56 UTC
In a file containing: 

Require Import List NArith.
Require Import ZArith.

if I jump after the second Require Import, I get in the log:

<value val="fail"><state_id val="0"/><richpp><_>
Anomaly:&nbsp;Not&nbsp;yet&nbsp;implemented,&nbsp;the&nbsp;GUI&nbsp;should&nbsp;not&nbsp;try&nbsp;this.&nbsp;Please&nbsp;report.</_></richpp></value>

This is because the state id sent for the second Add is the same as the first.

**Comment by psteckler** [comment] 2016-08-19 20:18
Race condition, the code is not waiting to send the second Require before the current state id is updated.

**Comment by psteckler** [comment] 2016-08-19 20:36
Actually, looks to be something simpler, the good value with the new state id is not being processed due to some failure in processing the (huge) entire response. The second Add is done after all the processing for the first response has finished.

**Comment by psteckler** [comment] 2016-08-19 20:53
With 8.5pl2, the error appears to be caused by ill-formed XML generated by coqtop. After a large number of feedbacks, there are several lines of the form:

<W> Grammar extension: in [tactic:simple_tactic], some rule has been masked

Then there are a couple more feedbacks, and finally the value containing the desired state id.

A workaround would be to delete characters from the buffer where the response is stored until we get valid XML, or the buffer is empty. Ugh.

**Comment by psteckler** [comment] 2016-08-19 21:21
In fact, that workaround makes this example work.

The ill-formed XML occurs with both 8.5pl2 and 8.6 for me.

I note that coqide does Set Silent, which I think suppresses the verbose output, including the bad XML. I can have PG do the same -- or use this hackish workaround.

**Comment by psteckler** [comment] 2016-08-22 15:49
The real problem here is that the Emacs process filter receives both stdout and stderr. There's no option to change that.

Not sure what the right solution is here.

**Comment by psteckler** [comment] 2016-08-23 21:19
I've committed a fix for this. The code now redirects stderr to /dev/null.

**Closed by psteckler** 2016-08-23 21:19 UTC
