### ISSUE TITLE
PG-xml handles anomalies extremely poorly (gets into a state where I have to kill emacs before I can use Coq again)

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#34] opened 2016-09-20 21:07 UTC
Evaluate to here twice: https://github.com/JasonGross/fiat-crypto/blob/bug/src/Specific/FancyMachine256/bug.v#L168

The log is https://github.com/JasonGross/fiat-crypto/blob/619054221422beb87437222e883515542a2501e3/src/Specific/FancyMachine256/coq-log

The tail of the log is:
```
*coqtop:
<value val="good"><unit/></value>
*emacs:
<call val="Add"><pair><pair><string>refine&nbsp;match&nbsp;e&nbsp;in&nbsp;exprf&nbsp;_&nbsp;_&nbsp;_&nbsp;t&nbsp;return&nbsp;inline_directive&nbsp;t&nbsp;with
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Op&nbsp;_&nbsp;t&nbsp;(OPshl&nbsp;as&nbsp;op)&nbsp;_
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Op&nbsp;_&nbsp;t&nbsp;(OPshr&nbsp;as&nbsp;op)&nbsp;_
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&gt;&nbsp;inline&nbsp;(t:=t)&nbsp;(Op&nbsp;op&nbsp;_)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;_&nbsp;=&gt;&nbsp;_
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;end.</string>
<int>-54</int>
</pair>
<pair><state_id val="55"/><bool val="true"/></pair>
</pair>
</call>

*coqtop:
<value val="fail"><state_id val="0"/><richpp><_>
Anomaly:&nbsp;Not&nbsp;yet&nbsp;implemented,&nbsp;the&nbsp;GUI&nbsp;should&nbsp;not&nbsp;try&nbsp;this.&nbsp;Please&nbsp;report.</_></richpp></value>
*emacs:
<call val="Add"><pair><pair><string>asdf

&nbsp;&nbsp;Definition&nbsp;AssembleSyntax&nbsp;:&nbsp;True.</string>
<int>-55</int>
</pair>
<pair><state_id val="55"/><bool val="true"/></pair>
</pair>
</call>

*coqtop:
<value val="fail"><state_id val="0"/><richpp><_>
Anomaly:&nbsp;Not&nbsp;yet&nbsp;implemented,&nbsp;the&nbsp;GUI&nbsp;should&nbsp;not&nbsp;try&nbsp;this.&nbsp;Please&nbsp;report.</_></richpp></value>
*emacs:
<call val="Add"><pair><pair><string>simple&nbsp;refine&nbsp;_.</string>
<int>-56</int>
</pair>
<pair><state_id val="55"/><bool val="true"/></pair>
</pair>
</call>

*coqtop:
<value val="fail"><state_id val="0"/><richpp><_>
Anomaly:&nbsp;Not&nbsp;yet&nbsp;implemented,&nbsp;the&nbsp;GUI&nbsp;should&nbsp;not&nbsp;try&nbsp;this.&nbsp;Please&nbsp;report.</_></richpp></value>
```

I'm going to switch back to the vanilla PG for a while, given that I don't actually need the features of this PG, and I'm spending about an order of magnitude more time tracking down bugs in PG than I am actually working on Coq developing.  (The tooling around error messages from Coq is one of the most important features to me, and PG-xml makes it rather frustrating to deal with Coq error messages, currently.)

**Comment by psteckler** [comment] 2016-09-27 17:52
The source of the error here is the interleaving issue mentioned in #28, now fixed. Just before the failure, there's an Edit_at call with state id 53, the result of an Undo or Goto within the locked region. Notice the call to Goal does not wait for the response, so the subsequent Add uses state id 55; it should be 53. That kind of error should not occur any longer.

Notice that the fail-value that reports the anomaly has a state id of 0, which offers no useful information. When that happens, PG uses the last known good state id, which in this case was 55, and Coq complains. If Coq instead offered the last valid state id, 53 here, then PG would re-synch, using its existing code. I'll suggest that, although there may be some justification for the current approach.

So what happened here is not really an error-handling issue in PG, it's that PG caused an error to begin with.

**Comment by JasonGross** [comment] 2016-09-28 22:22
I hit this again with a `pose proof`, after updating PG to today's version.  (Possibly caused by me spamming `C-c` to interrupt typeclass resolution search with `Typeclasses eauto := debug.`)  I think PG should specifically look for this message and do something sane.  In particular, it should not require *restarting emacs* to unbreak this.  Simply killing Coq is not enough; if I do that, then every subsequent invocation of Coq fails like this:
![image](https://cloud.githubusercontent.com/assets/396076/18934509/21efe1b0-85a8-11e6-902d-f92b217d480f.png)

**Comment by psteckler** [comment] 2016-09-29 19:26
Bug 5101 in the Coq Bugzilla is related to this issue. When an invalid state is submitted to Coq, it should respond with a valid state id. Instead, it either offers 0, conveying no information, or crashes. Fixing that on the Coq side is better, I think, than parsing responses.

If we do look for, say, "Anomaly", the best we can hope for is to retract the buffer and restart. There's probably a bug with restart, where it's not resetting the last valid state id. That's likely what's causing the crash.

**Comment by psteckler** [comment] 2016-09-29 20:32
I've committed a fix which I believe will allow you to restart Coq and proceed, if PG gets in a bad state.

**Comment by ejgallego** [comment] 2016-09-29 20:57
Note that indeed as pointed out by @gares in the WG, bug 5101 happens because PG is violating a XML protocol invariant (adding on top of an non open state).

The right action in this case for PG is to ignore the fail value (as weird as it seems)

**Comment by psteckler** [comment] 2016-09-29 21:15
If PG ignores the fail-value, it can't make any more progress, though. It would help if Coq sends back a good state id in the fail-value.

**Comment by ejgallego** [comment] 2016-09-29 21:22
I'm not sure I can agree. It is PG which sent an invalid XML protocol call in the first place, so what can Coq reply?

The current error is a bad form of "you request is invalid, try again". PG should be able to know which state was the last valid one.

Unfortunately the XML protocol doesn't provide an entry to `get_current_state ()`, also, the information in Fail is incomplete as it should contain the full `exn_info`. I dunno what to say here, I needed those so this is why I didn't use the XML protocol...

**Comment by psteckler** [comment] 2016-09-29 21:30
When PG sends a call, it's using the state id it thinks was the last valid one. If that state id is actually invalid, for whatever reason, and it doesn't get information on what a valid one is, it's stuck. It could maintain a stack of them, I suppose, and pop them until it succeeds. 

Could Coq not provide its notion of a valid state id in the fail-value, as it would if there were an error in the script?

**Comment by ejgallego** [comment] 2016-09-29 21:42
That is a possibility but would it imply changing the protocol? Indeed the problem here is that no state failed, the request is invalid. This can be solved in other protocols, dunno for the XML one.

However, if I understood the XML invariants correctly from the discussion "PG sends a call, it's using the state id it thinks was the last valid one. If that state id is actually invalid," is not supposed to happen.

Why did PG got out of sync wrt state validity? Is that a bug in PG, or do you think it is a bug in the protocol?

**Comment by psteckler** [comment] 2016-09-29 21:53
The issue that started this bug report was indeed a bug in PG, failing to interleave calls and responses, so that it sent the wrong state id. That should not happen now.

I'm not sure what happened after the interrupt request reported later, though. If Coq receives a SIGINT while it is idle, the next Add will send back a fail-value, and I think that contains a 0 (invalid) state id. PG should be able to recover from that, but without seeing a log, it's not clear to me what happened.

**Comment by ejgallego** [comment] 2016-09-29 22:15
Oh that's interesting. Does the XML protocol send an ACK for the interrupt?

We discussed behavior on interrupt briefly, I am not sure there is a way to interrupt Coq reliably with the XML protocol, neither pidetop can do it (relies on `check_for_interrupt`).

I think a possible interrupt recovery strategy is as follows: assume that all the states not confirmed after the interrupt ack will never be processed. With a minor tweak on the transactional stm code (to ensure signals are blocked between VCS commit and notification) this seems to work fine in SerAPI.

**Comment by psteckler** [comment] 2016-09-29 22:26
When the user types C-c C-c, PG first looks to see if it has a complete response to its last call. If so, it sends StopWorker messages for all workers not Dead or Idle. Otherwise, it sends a SIGINT. There's a race there, as mentioned, because Coq may have sent a response that PG has not yet processed.

If Coq is indeed processing something, so that check_for_interrupt shows the SIGINT was received, Coq sends a fail-value with a good state id, and PG sends an Edit_at, as usual. That works out well. 

And if Coq is really idle, and PG sends StopWorkers, good things happen again.

The in-between cases are dodgy.

**Comment by JasonGross** [comment] 2016-09-29 22:46
> but without seeing a log

Note that PG closes `*coq-log*` when Coq dies badly.  This makes it hard for me to give a useful log, sometimes.

**Comment by JasonGross** [comment] 2016-09-29 22:47
Also, sometimes PG hangs for unreasonably long when I try to interrupt, so I interrupt the interrupt with `C-g`.

**Comment by ejgallego** [comment] 2016-09-30 00:22
IMO Coq shouldn't send any response after SigInt, indeed that's the main race in the Ocaml side, the window between the commit of the transaction and sending the feedback. Blocking signals is necessary here (both in Coq and for example in SerAPI).

But indeed previous answers may arrive to PG after the signal has been sent, then IMO they should be all processed, as they should have been committed in the Coq side.

Personally I wouldn't check anything on C-c C-c but send `SigInt` right away. What is the benefit of stopping the workers from the PG side?

**Comment by ejgallego** [comment] 2016-09-30 12:11
So we had a bit more discussion this morning, and we have come up to the conclusion that interruption handling should be handled equally independently of who and why Coq is interrupted. Coq would notify the interruption the IDE, it marking where Coq has stopped.

So in this scenario, a "external" interruption, like a `StackOverflow`, is handled exactly the same.

**Comment by psteckler** [comment] 2016-09-30 20:18
Well, Enrico tells me that the StopWorkers messages are what CoqIDE does.

I'll have PG not flush the log buffer, and use some kind of marker to indicate between coqtop sessions.

**Comment by psteckler** [comment] 2016-09-30 20:28
I've add the end-of-session marker. The log buffer should stick around between restarts now.

**Comment by psteckler** [comment] 2016-10-03 14:26
If no one objects, I'm going to close this issue, because the bug that triggered the anomaly is no longer there (and the discussion has strayed from that). If PG does receive a fail-value with a state id of 0, that triggers a retraction to PG's last known good state. If the anomaly occurs again, there's some other bug to report.

**Comment by psteckler** [comment] 2016-10-04 16:18
Closing ... if the anomaly appears again, please file a new issue.

**Closed by psteckler** 2016-10-04 16:18 UTC
