### ISSUE TITLE
Multi-line notation in goals are not displayed correctly

### ISSUE THREAD

**Issue by RalfJung** [psteckler/ProofGeneral#69] opened 2017-01-23 13:02 UTC
To reproduce this issue, jump to the end of the following line in Iris: <https://gitlab.mpi-sws.org/FP/iris-coq/blob/23570f316a8f1681ef16e4bb7954b6c0f41b022e/theories/base_logic/lib/cancelable_invariants.v#L46>
(i.e., clone <https://gitlab.mpi-sws.org/FP/iris-coq.git>, check out commit 23570f316a8f1681ef16e4bb7954b6c0f41b022e, and go to line 46 of theories/base_logic/lib/cancelable_invariants.v)

This is how the server-protocol branch displays the goal:
```
...
  q : Qp
 ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
  ​"H1" : cinv_own γ 1
  "H2" : cinv_own γ q--------------------------------------∗False
```

This is how it looks in PG master and in CoqIDE:
```
...
q : Qp
______________________________________(1/1)
​"H1" : cinv_own γ 1
"H2" : cinv_own γ q
--------------------------------------∗
False
```

It seems like something about the newlines in the notation formatting confuses PG.

**Comment by psteckler** [comment] 2017-01-24 18:10
I'm able to reproduce this here. There's a newline that's getting lost. Looking into it.

**Comment by psteckler** [comment] 2017-01-24 18:20
The issue is caused by the translation from XML to Emacs S-expressions. There was a similar issue for spaces which were lost. I can use a similar technique here.

**Comment by psteckler** [comment] 2017-01-24 18:37
I've committed a fix. Please try it!

**Comment by ejgallego** [comment] 2017-01-25 16:45
Hi Paul, with the current version I see no newlines preserved at all.

**Comment by psteckler** [comment] 2017-01-25 16:48
On Wed, Jan 25, 2017 at 11:45 AM, Emilio Jesús Gallego Arias
<notifications@github.com> wrote:
> Hi Paul, with the current version I see no newlines preserved at all.

That's with 8.5 or 8.6? Do you have a short example?

**Comment by ejgallego** [comment] 2017-01-25 17:02
With 8.6, example:
```
Goal True /\ True .... [make it as long as you need for your screen]
```
The line never breaks.

**Comment by psteckler** [comment] 2017-01-25 17:10
I created a long goal like that, and the response from the released coqtop 8.6 is:

`<value val="good"><option val="some"><goals><list><goal><string>1</string><list/><richpp><_><constr.reference>True</constr.reference>&nbsp;<constr.notation>/\</constr.notation>
<constr.reference>True</constr.reference>&nbsp;<constr.notation>/\</constr.notation>
<constr.reference>True</constr.reference>&nbsp;<constr.notation>/\</constr.notation>
<constr.reference>True</constr.reference>&nbsp;<constr.notation>/\</constr.notation>
<constr.reference>True</constr.reference>&nbsp;<constr.notation>/\</constr.notation>
<constr.reference>True</constr.reference>&nbsp;<constr.notation>/\</constr.notation>
<constr.reference>True</constr.reference>&nbsp;<constr.notation>/\</constr.notation>`
...
where the newlines are significant. Those newlines are preserved in the \*goals\* buffer when I try it.

Are you using a different 8.6, maybe?

**Comment by ejgallego** [comment] 2017-01-25 17:27
I am using a recent 8.6 indeed, same result with released 8.6. I see the newlines in the buffer, however they are not preserved in the buffer. GNU Emacs 26.0.50.2

**Comment by psteckler** [comment] 2017-01-25 17:41
Not following. How do you see the newlines in the buffer, then, if they're not preserved? You see some, but not all, newlines?

**Comment by ejgallego** [comment] 2017-01-25 17:47
Sorry Paul if I am not clear. I see the newlines in the `*coq-log*` buffer, however not in the goal window. Screenshot attached:
![goals](https://cloud.githubusercontent.com/assets/7192257/22302366/c225640a-e32e-11e6-8aea-a812768e665c.png)

**Comment by psteckler** [comment] 2017-01-25 18:02
I see. But I'm not observing the same behavior here with 8.6 and Emacs 24.5.

Did you restart Emacs before running this? It might be that the unescaping is incorrectly using the 8.5 strategy. If you switched Coq versions, the unescaping strategy will be wrong (something else I need to take care of).

If that's not the issue, can you try editing the file `coq/coq-server.el`, and inserting a message in the function `coq-server--goal-goal`:

`(defun coq-server--goal-goal (goal)
  (let ((goal-goal (nth 4 goal)))
    (message "goal-goal: %s" goal-goal)
    (or ...`

Recompile PG.

The goal will show up in the minibuffer and also the \*Messages\* buffer. You should see an S-expression with some `#SPC#` and '#NL#` tokens, where the latter indicates a newline.

**Comment by ejgallego** [comment] 2017-01-25 18:08
Oh indeed, restarting emacs fixes that, thanks. c.f. #70

**Comment by psteckler** [comment] 2017-01-25 18:10
OK, I'm closing this issue, because Ralf's original complaint has been fixed, AFAIK.

**Closed by psteckler** 2017-01-25 18:10 UTC

**Comment by RalfJung** [comment] 2017-01-29 13:04
Indeed, I can confirm the fix. Thanks :)
