### ISSUE TITLE
Document can contain an error with no indication in the document status bar that there's an error

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#62] opened 2016-11-28 22:02 UTC
Can you spot the error here?

![image](https://cloud.githubusercontent.com/assets/396076/20687905/5aedd04e-b58c-11e6-91d8-3710afffb4e2.png)

Also, what's the keyboard shortcut for "move the cursor to the location of the next error"?

**Comment by psteckler** [comment] 2016-11-28 23:01
I see the error, but my eyes are good :-)

Can I get the code to reproduce the error?

I haven't yet implemented a keybinding to jump to the next error. Any key combination that you think would work well?

**Comment by JasonGross** [comment] 2016-11-28 23:44
Code:
```coq
Definition foo := 1.
Declare Reduction foo := cbv [ffo].
Definition bar := 1.
```

Evaluate to the end of the document.

I don't have an idea for a default key combination.  @cpitclaudel do you have thoughts ?

**Comment by cpitclaudel** [comment] 2016-11-28 23:52
There's already one in Emacs :) Should we reuse it?

```
next-error is an interactive compiled Lisp function in ‘simple.el’.

It is bound to C-x `, M-g n, M-g M-n.

(next-error &optional ARG RESET)

Visit next ‘next-error’ message and corresponding source code.

If all the error messages parsed so far have been processed already,
the message buffer is checked for new ones.

A prefix ARG specifies how many error messages to move;
negative means move back to previous error messages.
Just C-u as a prefix means reparse the error message buffer
and start at the first error.

The RESET argument specifies that we should restart from the beginning.
```

**Comment by ejgallego** [comment] 2016-11-29 00:34
Jason code produces a parse-time anomaly on the second sentence. However, the error-resiliency will allow for parsing to continue...

**Comment by JasonGross** [comment] 2016-11-29 02:58
@ejgallego certainly not a parsing error; I don't think Coq is so terrible that it modifies the parser at every definition.  In any case, I believe this has similar behavior, though I haven't tested it:
```coq
Definition foo := 1.
Opaque foo.
Declare Reduction foo := cbv [foo].
Definition bar := 1.
```

**Comment by ejgallego** [comment] 2016-11-29 09:39
Note that "parse-time error" != "parsing error". It is a "parse time error" for the returned error value has not `state_id` attached but an `edit_id`. Admitedly, the semantics of this part of the API are quite "fuzzy".

**Comment by psteckler** [comment] 2016-11-29 17:03
I've fixed the error count issue (an Elisp variable name was changed, not propagated everywhere).

**Comment by psteckler** [comment] 2016-11-29 17:23
It looks like I can have coq-mode have its own next-error-function, and then the keybindings for next-error will Do the Right Thing.

**Comment by psteckler** [comment] 2016-11-29 23:12
The Emacs key bindings for next-error should work now.

I tried (not so very hard) to get clicking on an error to make that the "current error", didn't work, but if there's sufficient demand, I can try harder.

Closing the issue, since I believe the mode line error count works again, and the key binding has been added.

**Closed by psteckler** 2016-11-29 23:12 UTC
