### ISSUE TITLE
Performance issues on large-ish files

### ISSUE THREAD

**Issue by RalfJung** [psteckler/ProofGeneral#82] opened 2017-02-11 13:12 UTC
The following file demonstrates some serious performance issues of this branch of PG on large-ish files: <https://gitlab.mpi-sws.org/robbertkrebbers/coq-stdpp/blob/master/theories/list.v>. The file is 3700 lines long and consists almost entirely of small lemmas with 1- or 2-line proofs. (That project has 0 dependencies, so you can easily try this yourself.)

Opening this file in CoqIDE, I can e.g. jump to the beginning of `join_nil_1`, and it takes <10sec until I can actually interactively look at that proof. During that time, the editor stays perfectly responsible. (It then takes really long to check all these proofs, way longer than just doing "make" on the console takes. Not sure why that is, but it is not a very severe problem and the proof that I look at interactively is processed as expected.)

In PG/emacs, if I do the same, emacs becomes pretty much entirely unusable after ~5-15 seconds: pressing an arrow key to navigate the cursor takes forever to react. After 2 minutes, the bar at the top is still more than 60% red. Effectively, this file cannot be worked on interactively.

**Comment by psteckler** [comment] 2017-02-14 16:36
I will look into this.

**Comment by psteckler** [comment] 2017-02-15 18:35
Behavior confirmed.

**Comment by psteckler** [comment] 2017-02-15 21:53
One source of slowness is the calculation of line numbers for the header line. With a lot of distinct script items, that bogs things down. I had tried a pre-processing step before, but abandoned that idea.

But even after disabling the header line, things are still slow. I've used the Elisp profiler, and don't see an obvious place to improve things.

**Comment by ejgallego** [comment] 2017-02-15 22:10
I heard once that many overlay operations were linear on the number of overlays, I dunno if that is true.

**Comment by psteckler** [comment] 2017-02-15 22:33
With async processing enabled but disabling the header line, using 2 or 4 workers, processing this file takes well over 2 minutes on my laptop. 

If I also disable async processing, the file completes in about 50 seconds on my laptop, reasonably fast. I don't know whether to laugh or cry. :-)

While async processing should be faster, it generates lots of feedbacks indicating worker statuses, which have to be parsed and processed.

**Comment by RalfJung** [comment] 2017-02-16 09:29
I am confused, what do you mean by "disabling async processing"? I thought the entire point of this branch was to use Coq's async support -- so, it "disabling async processing" equivalent to switching back to PG master?

**Comment by psteckler** [comment] 2017-02-16 16:33
Yes, the point of this branch is to enable async support. It can be disabled by setting the variable `coq-allow-async-proofs` to nil. Making that change passes command-line flags to coqtop that cause it to operate in syncronous mode. That's not quite equivalent to using PG master, because PG/xml still uses the XML protocol.

Sorry for the outburst, I was feeling a bit frustrated when I discovered that PG/xml is slower in async mode on this example. @gares suggests that it might be that in this particular example, where there are many small proofs, that the slowness could be on the Coq side. I need to see how fast CoqIDE is in async and synchronous mode on this example.

After looking at the Elisp profiling data with Clément yesterday, we have some ideas on how PG could be made faster. Those should make PG faster in both async and synchronous modes.

**Comment by psteckler** [comment] 2017-02-16 16:44
I just ran CoqIDE in both async and synchronous mode on this example. The time for both modes was about 30 seconds on my laptop. Note: I removed all files `list.*`, other than `list.v`, before running CoqIDE.

So the slowness is on the PG side, apparently.

**Comment by psteckler** [comment] 2017-02-16 17:52
More experiments. If I turn off updating colors in PG/xml, in async mode it still takes about 1m45sec to run this script, and about 50sec in sync mode. That suggests that the difference in time is due to the additional messages in async mode. I need to look at the profile results to confirm that.

**Comment by psteckler** [comment] 2017-02-16 19:11
The most expensive procedure is `coq-tq-log-and-send`. I had thought that was due to the thunk invocation that usually happens there. However, by commenting out some other calls in the procedure, the time for the procedure is reduced so that it takes very little time. I'm not yet sure which of the calls the time hog.

**Comment by psteckler** [comment] 2017-02-16 19:27
The expensive call inside `coq-tq-log-and-send` is the one that sets the end of the "sent" region.

**Comment by psteckler** [comment] 2017-02-16 19:51
Apparently, what's expensive about that call is the `save-excursion` and changing the point. If the call does nothing else, it's still expensive. Doing the same thing manually, saving the point and restoring it, instead of using that macro, is still expensive.

The other big time consumer is XML parsing.

**Comment by psteckler** [comment] 2017-02-17 16:51
One of the bottlenecks was specifying too many workers. I've changed the code to have Coq use the default number of workers.

**Comment by psteckler** [comment] 2017-02-17 17:56
I'm hoping I'll have something soon-ish that will make PG much faster on this example.

**Comment by psteckler** [comment] 2017-02-21 18:25
@gares has convinced me that the slowness on this example really is on the Coq side, not in PG. `coqc` creates a file `theories/.list.aux`. If you remove that file, CoqIDE becomes as slow as PG/xml on this file, because of the many small proofs. With the .aux file, CoqIDE with coqtop runs at the same speed as in sync mode, which is faster for this example. 

I'm still trying to work out why PG does not avail itself of the .aux file.

There are still some things I can make faster in PG, but doing those won't make it fast on this example, I'm afraid.

**Comment by ejgallego** [comment] 2017-02-21 19:18
Would you mind explaining what is the role of these "hints" file, why things are slower if they are missing; what info is contained in them?

**Comment by psteckler** [comment] 2017-02-21 19:34
My understanding is that these files contain timing information, and `coqtop` can use them to decide whether to delegate a proof to a worker. 

In the example for this issue, without the `.aux` file, all or most proofs are delegated, which creates overhead making things slower. With that file, `coqtop` knows it's faster not to delegate in this example, making things faster.

Maybe @gares can explain more.

**Comment by ejgallego** [comment] 2017-02-21 19:45
Oh I see now, indeed thanks a lot for the hints!

**Comment by psteckler** [comment] 2017-02-22 17:15
I made several changes to PG for this issue. The most significant change is to pass the filename to the Init call, which allows `coqtop` to use the `.aux` file. PG now uses the "vanilla" spans for coloring the buffer, the ones that contain state ids, instead of separate color spans. Also, PG uses a cheap calculation for line numbers, rather than exact line numbers. It can be inaccurate, but I hope good enough.

With these changes, PG/xml takes about 47 seconds on my laptop for this example, versus 41 seconds for vanilla PG. A bit of slowdown is expected, because vanilla PG doesn't have to parse XML, does less coloring, and doesn't have a header line.

As the earlier discussion indicates, this example is not a good candidate for async processing.

**Comment by psteckler** [comment] 2017-02-27 22:27
I've PG/xml down to 43 seconds on this example.

I've removed the "help span" feature. That feature creates the Show/Hide context menus. But it's broken in vanilla PG, doesn't seem to be much used, and a better version of the functionality is available via Company-Coq. 

Also, I removed another use of save-excursion that's used when updating the response buffer.

With those changes, the Elisp profiler indicates that the two most expensive calls are for XML parsing and GC, which are both unavoidable. So I think I've squeezed a lot of the fat out of the code.

**Comment by ejgallego** [comment] 2017-02-27 22:50
Great. Do you have a ballpark number for the time spent in parsing?

**Comment by psteckler** [comment] 2017-02-27 23:01
The profiler says XML parsing is about 16% of the time (and GC is 10%).

**Comment by ejgallego** [comment] 2017-02-27 23:06
So ≈ 7 secs. Thanks!

**Comment by psteckler** [comment] 2017-02-27 23:28
It's less than that. I believe the Elisp profiler is only counting time spent in Elisp code, ignoring C code underneath, and also any time waiting for user input. These things are not so well-documented, though.

I instrumented the parsing call to see how much time is spent there, and it's a bit less than 1.5 seconds on this example.

**Comment by psteckler** [comment] 2017-02-27 23:32
And I also tried the elp profiler on that function, which gives a similar number (1.43 seconds).

That's a different Elisp profiler that can be used to profile individual functions. The usual profiler examines all the code, and gives you percentages, rather than absolute times.

**Comment by ejgallego** [comment] 2017-02-28 00:06
I see, thanks!

**Comment by psteckler** [comment] 2017-03-02 20:58
Can we close this issue?

Getting PG to use the `.aux` file was the main performance impediment for this file, and there have been a few other performance fixes.

**Comment by psteckler** [comment] 2017-03-07 22:27
Closing, think performance is acceptable now.

**Closed by psteckler** 2017-03-07 22:27 UTC

**Comment by RalfJung** [comment] 2017-03-24 15:25
Performance seems very good now, thanks a lot!

**Comment by psteckler** [comment] 2017-03-24 15:46
Good to hear, I'm relieved. :-)
