### ISSUE TITLE
enhancement: highlighting to distinguished processed from yet-to-process proofs in locked region

### ISSUE THREAD

**Issue by jonleivent** [psteckler/ProofGeneral#20] opened 2016-09-17 00:43 UTC
The bright blue highlighting of a proof that is being processed is nice, but one cannot differentiate between which proofs have been processed (but not Qed-ed) vs. those yet to be processed at all, when all are in the pale blue locked region.  It would be nice if these were all different colors.

**Comment by jonleivent** [comment] 2016-09-17 01:41
Also a way to tell when Checking is completely done for the locked region in the bufffer - other than scrolling around looking for (the absence of) a bright blue Qed.  Maybe gray-out the Check button itself?

**Comment by gares** [comment] 2016-09-19 04:12
CoqIDE and Coqoon (and Isabelle/Jedit) do provide a "gutter" widget to display the overall status of the document.

**Comment by psteckler** [comment] 2016-09-19 19:12
The pale blue color in the locked region is placed before sending anything to Coq. After sending a statement to Coq, when we get a message back saying the statement is being processed, we color it dark blue. Currently, when we get a subsequent message saying that processing is complete, we remove the dark blue, leaving the pale blue. For that step, we could instead color it something else, say green a la CoqIDE. Would that help?

**Comment by psteckler** [comment] 2016-09-19 19:18
For the Check button, we could disable it as soon as it's pressed. When the user sends another statement, or makes an edit in the buffer, we could re-enable it. (Can the Check fail?)

**Comment by JasonGross** [comment] 2016-09-19 19:28
Note that this difference is not easily visible in console emacs, which uses underlines by default.  Currently I set `proof-locked-face` for the "finished" one; what should I set to get colors for errored regions, and for processing regions?

**Comment by jonleivent** [comment] 2016-09-19 19:47
@psteckler : if we have 3 faces we can set (locked-to-be-processed, locked-processing, locked-processed), then probably we just need to play with them to figure out a nice default config.

As for the Check button - I don't know if sending another statement should always enable it.  For instance, if I send the statement "Check Foo." that does nothing to the proof state.  Is there no way to tell if there is pending stuff to check or not?

**Comment by psteckler** [comment] 2016-09-19 20:41
@JasonGross : There are new faces for 

  - the "processingin" feedback, proof-processing-face
  - the "incomplete" feedback, proof-incomplete-face
  - the secondary locked region created when a focus is opened via backtracking, proof-secondary-locked-face

It looks like we'll be creating a few face for the processed statements, rather than simply removing the proof-processing-face for them.

@jonleivent : Statements like "Check Foo." can be sent from menus, and maybe via key bindings. Statements that change the proof state are never sent in that way. So a reasonable approximation would be to enable the Check button for statements in scripts, but not for statements/queries sent via menus and key bindings.

**Comment by psteckler** [comment] 2016-09-28 21:45
I think we can build a poor man's gutter widget using the Emacs mode line for the \*response\* buffer.  

I've confirmed that you can set text properties on the Emacs mode line. We can make the mode line a sequence of thin spaces, colored according to the corresponding location of the script buffer. I think we can use the existing faces, so the colors will match. It's also possible to make locations in the mode line mouse-sensitive, so clicking on the mode line will jump to the corresponding script location.

Does this sound like a good approach?

**Comment by psteckler** [comment] 2016-09-28 21:49
I've just learned there's a "hair space" character in Unicode, thinner than a thin space. That should allow the gutter-widget-on-the-cheap to show fine distinctions.

**Comment by jonleivent** [comment] 2016-09-28 22:29
Interesting choice - the *response* buffer mode line.  But, not everyone will have the response buffer visible.  There's also delete-empty-panes mode, which will make it invisible at times, right?  If you can do something in the script window that would obviously be better.  What about the script window's left or right fringe?  I'm sure @JasonGross will object on the grounds that VT52s don't show fringes well ;-)

**Comment by psteckler** [comment] 2016-09-29 17:05
In addition to the mode line, Emacs buffers can also have a header line, which appears at the top of the buffer window. We could place an (optional) header line over the script buffer as the gutter widget.

**Comment by psteckler** [comment] 2016-09-29 22:32
Does the header line sound viable?

Another approach would be to create an empty buffer with an empty window, and put its mode line just below the script buffer's mode line. That's more complex, though. I've tried creating a multi-line mode line to get the same effect, Emacs won't do it.

**Comment by gares** [comment] 2016-09-30 11:01
Without a screenshot I can hardly imagine what you propose ;-)

**Comment by psteckler** [comment] 2016-09-30 19:45
Here's what it looks like using an empty buffer below the script buffer, with some colors in the mode line:

![empty-buffer](https://cloud.githubusercontent.com/assets/2244648/19004264/1032c40c-8723-11e6-85d4-8f9119f772be.png)

I didn't manage to find a way to make the empty buffer disappear entirely, so maybe this one's a non-starter.

Here's a header line above a script buffer:

![emacs-header-line](https://cloud.githubusercontent.com/assets/2244648/19004649/d336eb8a-8724-11e6-93a6-3ba8a31f5ec6.png)

**Comment by psteckler** [comment] 2016-09-30 19:59
You can change the height of the header line by changing the height of the face used. In the screenshot above, the header line is the same height as the mode line, but could be made narrower or wider.

**Comment by jonleivent** [comment] 2016-09-30 20:19
I think the header line is a good solution.

**Comment by psteckler** [comment] 2016-10-04 18:11
I've implemented this and committed it:
![header-line](https://cloud.githubusercontent.com/assets/2244648/19086488/62f6c992-8a3c-11e6-8eaf-010fb7b565a5.png)
Double-clicking on the header line moves the cursor to (approximately) the corresponding location in the buffer.

**Comment by psteckler** [comment] 2016-10-04 18:54
I've discovered this setup doesn't do much on a text terminal.

Maybe the characters in the header line could be changed, rather than the colors, in response to feedbacks.

**Comment by psteckler** [comment] 2016-10-04 19:47
I've found a way to do something meaningful here with text terminals. Working on it.

**Comment by psteckler** [comment] 2016-10-04 22:53
Committed code to make this work with TTYs.  Doesn't respond to mouse clicks, so not sure how useful this is.

**Comment by JasonGross** [comment] 2016-10-05 00:45
It'll still be pretty useful for seeing, at a glance, whether or not the document has any errors.

**Comment by jonleivent** [comment] 2016-10-05 16:02
I like the new header line a lot.  I still wish there were more colors to distinguish between processed proofs vs. yet-to-be processed proofs (as in CoqIDE), not just by looking at the color of the Qed.

**Comment by psteckler** [comment] 2016-10-05 16:28
Yes, that can be added, just haven't done it yet.

**Comment by psteckler** [comment] 2016-10-05 16:32
Here's a possible tweak to the header line. Right now, the width of a color is proportional to the size of the script. For a short script, then a color representing a single span can get a lot of width in the header line, which looks odd to me. I could make it so the number of characters in the header line is no more than the number of lines taken up by the colored span in question.

**Comment by jonleivent** [comment] 2016-10-05 17:00
Yes - it makes sense that each char in the header line represents no less than a line in the script.

**Comment by psteckler** [comment] 2016-10-05 18:41
I've made that change.

**Comment by psteckler** [comment] 2016-10-05 19:17
I've added coloration for processed lines, green, a la CoqIDE, which also shows up in the header line. 

This may be jarring -- or pleasing -- to old PG hands. 

How does it look?

**Comment by jonleivent** [comment] 2016-10-05 19:37
Jarring, indeed!  I can't even see the proof text through that dark being-processed blue color.

I would have preferred that the most quiescent state (all proofs processed) has the most calming color (all pale blue).  The jarring green would be a good color for a vary transitory state, such as tactics being processed.  Then some color that is less jarring for yet-to-be-processed, which is a quiescent state when in lazy mode, after all.  That new dark blue is not working at all.

But, if these colors are all customizable, then just tell us the names of the face options.  The defaults should still be less off-putting, but are less problematic, as I suspect most Emacs users are quite familiar with customization of faces.

**Comment by psteckler** [comment] 2016-10-05 19:48
Yes, I've fixed that dark blue color. That was my attempt to harmonize an RGB string and the word "darkblue" that appeared in the face table. Try again.

There's a problem with ordering, though. Sometimes the "incomplete" message comes before a "processed" message, and when a span is colored, the ordering matters. I've worked out a priority system for the header line, but haven't worked out something for the script colors.

**Comment by psteckler** [comment] 2016-10-05 20:00
I was able to reuse the face ranking system for the script, too.

**Comment by jonleivent** [comment] 2016-10-05 21:10
It's better that the dark blue is gone, but I'd still prefer to set these faces to something else.

As I step through a proof, I'm seeing at least 5 different colors involved: white, pink, light blue, medium blue, green.  What are these states?  I can tell that (obviously) white is not processed, and green is fully processed.  I am guessing that pink is to-be-queued, light blue is queued, and medium blue is being processed.  Is that right?  So, the transition diagram is:

`white -> pink -> light blue -> medium blue -> green.`

Then there's also the colors of the Qed/Defined lines, which apparently encode the fact that in async=on and async=lazy, a whole proof can be in two states: not kernel checked and kernel checked.  For not-kernel-checked, the Qed/Defined is medium blue, for kernel-checked it is green.  One confusing thing here is that the medium-blue Qed/Defined shows up early - the rest of that proof might still be light blue.  Also confusing is that this medium-blue does not represent active processing, as it does in the rest of the proof.  Is there a 3rd state for Qed/Defined that represents that the kernel is actively processing it?  Maybe my proofs don't show this state well.

Also, the parts of the locked region that are not parts of a proof stay light blue.  In vanilla PG, that makes sense, but probably not in PG xml.

Anyway, my point is (perhaps?) that the states and state transitions should be clarified first, otherwise discussion about colors just adds a layer of confusion...

Sorry for babbling...

**Comment by psteckler** [comment] 2016-10-05 21:41
The colors are defined in generic/proof-faces.el, and for the header line, coq/coq-header-line.el.

Pink (proof-queued-face) means in PG's internal queue.
Light blue (proof-locked-face) indicates the locked region, because script has been placed in transactional queue for sending to Coq.

Those colors came from vanilla PG. The only difference is that the locked region indicated that the script had been directly sent to Coq. So lightblue in PG-XML does not mean that Coq has been sent that piece of the script.

The new colors in PG-XML are:

The lightskyblue (proof-processing-face) is shown in response to feedbacks with the `processingin' value. In PG-XML, this means Coq has seen and is processing that bit of script.
The green (proof-processed-face) is shown for `processed' feedbacks. That means Coq is done processing that bit.
The blue (proof-incomplete-face) is shown for `incomplete' feedbacks for Qeds.

When you kernel-check a proof, there's a `complete' feedback, in which case PG removes the blue, revealing the green (processed) color, which has lower priority.

The light blue color still makes some sense, because PG uses the notion of the locked region to know how much of the script has been processed, from PG's (not Coq's) point of view. When you do proof-goto-point, the light blue locked region is made to extend to the cursor location.

This is my (perhaps flawed) understanding, at least.

**Comment by psteckler** [comment] 2016-10-11 17:04
Is the current implementation of this enhancement -- using the green color -- acceptable?

Can the issue be closed?

**Comment by jonleivent** [comment] 2016-10-11 19:03
Just pulled again, and taking a fresh look - I want to see if I can set the faces...

**Comment by jonleivent** [comment] 2016-10-11 19:35
Is there a way to have a proof-unprocessed-face instead of a proof-processed-face, such that proof-locked-face doubles as the processed face instead of the unprocessed face?  In other words, I'd like to have a fully proved locked region be all one face (the proof-locked-face), as it is in vanilla PG.  Then, have colors show deviations from that.  I can't seem to get that with the current set of faces in PG xml.

**Comment by psteckler** [comment] 2016-10-11 19:53
The proof-locked-face is used to indicate what part of the script buffer has been processed on the PG side, and that's always contiguous block. If proofs are processed asynchronously, the processed bits might consist of any number of blocks within proofs, and they might become processed in any order. In this world, the locked region is distinct from the processed region. You've probably noticed that comments within the locked region never turn green, because they're not even sent to Coq.

In synchronous mode, we could probably do something like you suggest -- but you could be using vanilla PG in that case.

**Comment by psteckler** [comment] 2016-10-11 19:57
Another idea would be to have the header line not mention the locked and queued spans. Then, if the header line were all green -- without any gaps -- the script would be fully proved.

**Comment by psteckler** [comment] 2016-10-11 21:38
That might be too hard to implement, and maybe too hard to understand.

Another thought: PG can count the number of spans it's queued for submission (those in the locked region), then get the percentages of those that are in-processing, and those that are processed, and display those numbers either in the header line or in the mode line. When the processed percentage is 100%, the script is fully processed.

**Comment by jonleivent** [comment] 2016-10-11 21:48
What if there is both a proof-processed-face and a proof-unprocessed-face.  By default, proof-unprocessed-face is set to be proof-locked-face and proof-processed-face is green.  That gives the same appearance as the current default config of PG xml.

Then, if others have a preference similar to mine (if not, then I'm willing to lose this argument), they can set proof-processed-face to be the same as proof-locked-face and set proof-unprocessed-face to something that stands out.

**Comment by psteckler** [comment] 2016-10-11 23:25
There is a proof-processing-face already, so that can be your proof-unprocessed-face.

With the first setup, you would get notification that Coq has finished processing a span, but not that it's working on it. That's a little different than the current default.

In the second setup, you'd see when Coq is working on something, but you wouldn't be able to distinguish when Coq has finished something from those bits that PG has examined, but not yet sent to Coq.

A user could use the currently-available face names to do either of those.

I've got the colors and percentages on the mode line code almost working, should have something tomorrow.

**Comment by psteckler** [comment] 2016-10-12 18:38
I added the mode-line information, which shows the processing and processed percentages of the spans in the buffer. The spans are created when queuing script statements. 

We don't know how many spans there will be in the yet-to-be-processed part of the buffer, which you need to keep in mind when interpreting the percentages. So if you have a 1000-line script, and you submit just one line, and you get a processed message, the processed percentage will be 100%.

**Comment by jonleivent** [comment] 2016-10-14 17:22
I really like the mode-line info, but what is the first %?  It is almost always 0% in lazy mode, even after clicking on Check.  I see it climb and fall in non-lazy mode.  Is it the current % of the locked region being processed by background tasks?  That's an unusual piece of info to think about...

A really nice addition would be tooltips for the mode-line info.

As for faces: I am still not sure we are understanding each other about these.  But, maybe it isn't worth trying to sort this issue out much more.  The second % in the mode line - which apparently has as its numerator the commands in the locked region that have been processed, and has as its denominator the total number of commands in the locked region - is what I'll focus on insead when trying to determine if there is pending work to be done.  That and the final mode line number - which is apparently the number of Qeds in the locked region yet to be verified by the kernel.

I'm also assuming that the %'s are rounded down - so that 100.0% is only possible when the numerator = denominator.  If not, I might prefer just seeing the difference instead of the ratio - such that 0 would be the target instead of 100.0%.

**Comment by psteckler** [comment] 2016-10-14 17:34
The first percentage is for the spans with the "processing" color, the darker blue. Often these turn to green almost immediately, which is why it becomes 0. But not always ... maybe it's not worth putting on the mode line.

OK, I'll look into tooltips ... I know that can be done on buffer text, not sure about the mode line.

It's easy enough to aim to 0 for the processed percentage. I hope others will offer opinions on this.

**Comment by psteckler** [comment] 2016-10-14 17:42
I've added tooltips ... see if the text is OK.

**Comment by jonleivent** [comment] 2016-10-14 18:00
The tooltip text looks OK.  I agree that the first % may not be worth showing.  No reason to clutter the mode line more than needed, as some Emacs users already push the limits there.

But I just got into a state in normal async mode where the processed (second) % is 99.6% and isn't going up, and there are 3 yet-to-be-kernelized Qeds.  And, clicking on Check does nothing more.

How did I manage that?  I put "gfail" tactics into 2 proofs so that I could see the new errors mode-line count work - and it did.  Then I removed the fails and did a GoTo to relock the region, then clicked Check.

**Comment by psteckler** [comment] 2016-10-14 19:16
Not sure I can reproduce that -- I tried, but got back to 100%. It's possible a extra span got created somehow, which would invalidate the computation. If you can work out exact steps, that would help.

**Comment by psteckler** [comment] 2016-11-10 16:25
Maybe this issue can be closed now. Currently, the "sent" region, colored pale blue, is extended when script items are sent to Coq. The actual items remain pink until Coq indicates it's working on them, when they become darker blue, and another pale blue when Coq finishes with them. Does the pink-to-darker-blue transition address the original issue raised here?

**Comment by jonleivent** [comment] 2016-11-10 20:57
I am OK with the latest colorization state (version b5794da).

**Closed** 2016-11-10 21:45 UTC
