### ISSUE TITLE
C-g confuses PG

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#47] opened 2016-10-04 20:21 UTC
It should not be possible to get PG into a state where it has some red lines that don't show up in the progress bar, with in-progress processing lines below them that are not being processed
![image](https://cloud.githubusercontent.com/assets/396076/19090916/8565bf9e-8a4e-11e6-9dcf-25d014a750f9.png)

**Comment by psteckler** [comment] 2016-10-05 20:50
To debug this, I need to know the steps that put Emacs into this state.

**Comment by psteckler** [comment] 2016-11-17 21:02
Going to close this one, because:

 1) Not sure how to reproduce it, and
 2) I've wrapped the code that sends script to Coq with inhibit-quit. On the receiving side, there is already an Emacs-automagically-provided inhibit-quit for the process filter. If I do C-g with the current code, and have debug-on-quit enabled, the only stack trace I see is for Emacs' internal redisplay function, never any of the PG code.

**Closed by psteckler** 2016-11-17 21:02 UTC
