### ISSUE TITLE
Sometimes evaluation fails with no displayed error message

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#59] opened 2016-11-28 21:56 UTC
![vokoscreen-2016-11-28_16-54-33](https://cloud.githubusercontent.com/assets/396076/20687719/9d0978ee-b58b-11e6-81c8-c49b85def77c.gif)

**Comment by psteckler** [comment] 2016-11-28 22:49
Can you enable logging and see what the XML traffic is there?

M-x set-variable, proof-server-log-traffic, t, or modify the setting in generic/proof-config.el and re-compile.

Sometimes, there are feedbacks indicating errors for state id's that haven't yet occurred. The strategy has been to queue those feedbacks on the assumption they'll arrive. Maybe we should just print the error, even though there's no script item associated with it.

**Comment by JasonGross** [comment] 2016-11-28 23:46
The code in #28 reliably reproduces this.

```xml
*emacs:
<call val="Init"><option val="none"/></call>

*coqtop:
<value val="good"><state_id val="2"/></value>
*emacs:
<call val="Add"><pair><pair><string>Remove&nbsp;Search&nbsp;Blacklist&nbsp;&quot;Private_&quot;&nbsp;&quot;_subproof&quot;.&nbsp;
Add&nbsp;Search&nbsp;Blacklist&nbsp;&quot;Private_&quot;&nbsp;&quot;_subproof&quot;.</string>
<int>-3</int>
</pair>
<pair><state_id val="2"/><bool val="true"/></pair>
</pair>
</call>

*coqtop:
<value val="good"><pair><state_id val="3"/><pair><union val="in_l"><unit/></union><string></string></pair></pair></value>
*emacs:
<call val="SetOptions"><list><pair><list><string>Printing</string>
<string>Depth</string>
</list>
<option_value val="intvalue"><option val="some"><int>50</int>
</option>
</option_value>
</pair>
</list>
</call>

*coqtop:
<value val="good"><unit/></value>
*emacs:
<call val="SetOptions"><list><pair><list><string>Printing</string>
<string>Width</string>
</list>
<option_value val="intvalue"><option val="some"><int>99</int>
</option>
</option_value>
</pair>
</list>
</call>

*coqtop:
<value val="good"><unit/></value>
*emacs:
<call val="Add"><pair><pair><string>Require&nbsp;Import&nbsp;Top.B.</string>
<int>-4</int>
</pair>
<pair><state_id val="3"/><bool val="true"/></pair>
</pair>
</call>

*coqtop:
<feedback object="state" route="0"><state_id val="3"/><feedback_content val="processingin"><string>master</string></feedback_content></feedback>
*coqtop:
<feedback object="state" route="0"><state_id val="2"/><feedback_content val="processed"/></feedback>
*coqtop:
<feedback object="state" route="0"><state_id val="3"/><feedback_content val="processed"/></feedback>
*coqtop:
<feedback object="state" route="0"><state_id val="4"/><feedback_content val="processingin"><string>master</string></feedback_content></feedback>
*coqtop:
<feedback object="state" route="0"><state_id val="3"/><feedback_content val="processed"/></feedback>
*coqtop:
<feedback object="state" route="0"><state_id val="4"/><feedback_content val="message"><message><message_level val="error"/><option val="some"><loc start="15" stop="20"/></option><richpp><_><message.error>Error:</message.error>&nbsp;Cannot&nbsp;find&nbsp;a&nbsp;physical&nbsp;path&nbsp;bound&nbsp;to&nbsp;logical&nbsp;path&nbsp;matching&nbsp;suffix&nbsp;Top.</_></richpp></message></feedback_content></feedback>
*coqtop:
<value val="fail" loc_s="15" loc_e="20"><state_id val="3"/><richpp><_>
<message.error>Error:</message.error>&nbsp;Cannot&nbsp;find&nbsp;a&nbsp;physical&nbsp;path&nbsp;bound&nbsp;to&nbsp;logical&nbsp;path&nbsp;matching&nbsp;suffix&nbsp;Top.</_></richpp></value>
*emacs:
<call val="Edit_at"><state_id val="2"/></call>

*coqtop:
<feedback object="state" route="0"><state_id val="2"/><feedback_content val="processed"/></feedback>
*coqtop:
<value val="good"><union val="in_l"><unit/></union></value>
*emacs:
<call val="Goal"><unit/></call>

*coqtop:
<feedback object="state" route="0"><state_id val="2"/><feedback_content val="processed"/></feedback>
*coqtop:
<value val="good"><option val="none"/></value>
*emacs:
<call val="Status"><bool val="false"/></call>

*coqtop:
<feedback object="state" route="0"><state_id val="2"/><feedback_content val="processed"/></feedback>
*coqtop:
<value val="good"><status><list><string>Top</string></list><option val="none"/><list/><int>0</int></status></value>
```

I think the error message should almost always be printed.

**Comment by psteckler** [comment] 2016-11-29 23:15
In this case, this state id \*has\* been assigned, so there's some bug underneath. Will investigate.

**Comment by psteckler** [comment] 2016-11-30 17:07
What's happening is:
  - there's an error feedback received with a never-received state id (4 in your XML), so there's no statement associated with that state id, so the feedback gets queued in anticipation of receiving it
  - then there's a fail-value with a state id corresponding to the state just before the bad Require (3 here)
  - that triggers an Edit_at from PG, which reasons, there's no statement for that state id, and (correctly) uses the initial state id (2 in the XML)

This is related to https://coq.inria.fr/bugs/show_bug.cgi?id=4972.

CoqIDE does show the error, not sure how. The feedback refers to a non-existent state id, while the fail-value, which also has the error message, uses a state id not associated with any statement. I'll see if Enrico can clarify.

**Comment by psteckler** [comment] 2016-11-30 17:20
I have an idea of how to do this. I've sent it to Enrico, and will try it out.

**Comment by gares** [comment] 2016-11-30 17:40
I'm not sure I follow.  The error message is there twice, once in a feedback (on 4) and one of the result of Add.
Also it seems to signal 3 as a safe state id, I don't get why you backtrack to 2.

**Comment by psteckler** [comment] 2016-11-30 18:22
Right, the feedback's state id is 4, there's no good-value with that state id, and hence no script item to attach the error message to.

The fail-value has a state id of 3, but there's no script statement associated with that state id. That state id came from PG sending the blacklist boilerplate, again there's no script item for it.

For a fail-value, PG tries to retract to the \*point\* associated with the safe state id, rather than directly sending the state id. Since there's no statement in this case, it uses the minimum point in the buffer, which is correct in this case. In the PG code, that gets special-cased to use the initial state id in the Edit_at.  If I put in some good statement before the offending Require, the Edit_at will have the state id in the fail-value.

That's kind of a baroque setup, indeed; the code is making use of already-existing machinery for doing retractions.

There needs to be a way to associate the error message with a script statement. I can't see how to do that with the feedback, since the state id appears nowhere else. For the fail-value, one can plausibly associate its state id with the statement Add'ed using that state id.

**Comment by JasonGross** [comment] 2016-11-30 18:26
> Since there's no statement in this case, it uses the minimum point in the buffer, which is correct in this case.

Shouldn't it instead use the valid state immediately before the blacklist boilerplate?

**Comment by psteckler** [comment] 2016-11-30 18:30
Those coincide here. In the XML above, it's the state id "2".

(When I ran the file, it was "1", which is what I usually see after the Init call.)

**Comment by psteckler** [comment] 2016-11-30 21:53
I've committed code that addresses the issue here.

There's now a table that associates script spans with the state id when they're sent. When a fail-value is received, the error message and corresponding locaton are recorded in the code, and when the good-value is received for the triggered Edit_at, the error message is finally marked in the script.

Please try it!

**Comment by psteckler** [comment] 2016-12-01 16:27
Closing, since the issue is fixed, as best I know.

**Closed by psteckler** 2016-12-01 16:27 UTC
